apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Koa\Desktop\kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: catalogue
  name: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: catalogue
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Koa\Desktop\kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: catalogue
    spec:
      containers:
        - image: weaveworksdemos/catalogue:0.3.5
          name: catalogue
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - all
            readOnlyRootFilesystem: true
      hostname: catalogue
      restartPolicy: Always
