apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Koa\Desktop\kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: front-end
  name: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: front-end
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Koa\Desktop\kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: front-end
    spec:
      containers:
        - image: weaveworksdemos/front-end:0.3.12
          name: front-end
          securityContext:
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
      hostname: front-end
      restartPolicy: Always
