apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Koa\Desktop\kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: orders-db
  name: orders-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orders-db
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Koa\Desktop\kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: orders-db
    spec:
      containers:
        - image: mongo:3.4
          name: orders-db
          securityContext:
            capabilities:
              add:
                - CHOWN
                - SETGID
                - SETUID
              drop:
                - all
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: orders-db-tmpfs0
      hostname: orders-db
      restartPolicy: Always
      volumes:
        - emptyDir:
            medium: Memory
          name: orders-db-tmpfs0
