apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Koa\Desktop\kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: shipping
  name: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: shipping
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Koa\Desktop\kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: shipping
    spec:
      containers:
        - env:
            - name: JAVA_OPTS
              value: -Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
          image: weaveworksdemos/shipping:0.4.8
          name: shipping
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - all
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: shipping-tmpfs0
      hostname: shipping
      restartPolicy: Always
      volumes:
        - emptyDir:
            medium: Memory
          name: shipping-tmpfs0
