apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Koa\Desktop\kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: user
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Koa\Desktop\kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: user
    spec:
      containers:
        - env:
            - name: MONGO_HOST
              value: user-db:27017
          image: weaveworksdemos/user:0.4.4
          name: user
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - all
            readOnlyRootFilesystem: true
      hostname: user
      restartPolicy: Always
